server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
#  使用registerWithEureka和fetch-registry为false 表示自己是一个server
    registerWithEureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/