eureka:
  client:
    service-url:
      defalutZone: http://localhost:8761/eureka/

server:
  port: 9875
  servlet:
    context-path: /fiegn

spring:
  application:
    name: service-fiegn

feign:
  hystrix:
    enabled: true